train_dataset:
  dataset:
    name: math-function
    args:
      k_values: [2, 3, 4, 5, 6]
      resolution: 1024
      num_functions: 1000
      repeat: 20
      cache: in_memory
  wrapper:
    name: math-function-downsampled
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16

val_dataset:
  dataset:
    name: math-function
    args:
      k_values: [2, 3, 4, 5, 6]
      resolution: 1024
      num_functions: 100
      repeat: 160
      cache: in_memory
  wrapper:
    name: math-function-downsampled
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 16

data_norm:
  inp: {sub: [0.0], div: [1.0]}
  gt: {sub: [0.0], div: [1.0]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
        n_colors: 1
    imnet_spec:
      name: thera-simple
      args:
        out_dim: 1
        hidden_dim: 256
        num_frequencies: 64
        kappa: 1.0

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100 